language: php

php:
  - 5.4

env:
  - WP_VERSION=latest WC_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WC_VERSION=latest WP_MULTISITE=0

before_script:
  - bash tests/bin/install.sh wc_memberships root '' localhost $WP_VERSION $WC_VERSION

script: phpunit